### ISSUE TITLE
improve the readme

### ISSUE THREAD

**Issue by oliveira-emmanuel** [emmanuelmarcosdeoliveira/oliveira-portifolio#7]
Make a Readme more   attractive
@emmanuelmarcosdeoliveira

**Comment by emmanuelmarcosdeoliveira** [comment]
done
- [x] readme update ✔️
![image](https://github.com/emmanuelmarcosdeoliveira/oliveira-portifolio/assets/116108389/56a807ae-ce88-4410-a79c-5974e402d2a9)
